/**
 * js/candidates.js
 * ------------------------------------------------------------
 * Candidate management page: evaluate (create), edit (update),
 * delete, search/sort/filter, render results, and export reports.
 * All evaluation math happens server-side; this file orchestrates
 * the UI and API calls.
 */

(function () {
  "use strict";

  const { $, toast, setLoading, escapeHtml, setFieldError, clearErrors, debounce, downloadText } = window.UI;

  const FIELD_IDS = ["candidate_name", "age", "education", "skill_score", "projects", "relocate"];
  const CONFIDENCE_PERCENT = { High: 90, Medium: 60, Low: 30 };

  let editingId = null;     // null = create mode, otherwise update mode
  let cache = [];           // last fetched list (for client-side report export)

  /* ---------- Helpers ---------- */

  function statusInfo(c) {
    if (c.priority_status) return { label: "Priority", cls: "pill pill-orange", badge: "status-priority" };
    if (c.eligibility === "Eligible") return { label: "Eligible", cls: "pill pill-green", badge: "status-eligible" };
    return { label: "Not Eligible", cls: "pill pill-red", badge: "status-not" };
  }

  function readForm() {
    return {
      candidate_name: $("#candidate_name").value.trim(),
      age: parseInt($("#age").value, 10),
      education: $("#education").value,
      skill_score: parseInt($("#skill_score").value, 10),
      projects: parseInt($("#projects").value, 10),
      relocate: $("#relocate").value,
    };
  }

  function validate(data) {
    clearErrors(FIELD_IDS);
    let ok = true;
    if (!data.candidate_name || data.candidate_name.length < 2) { setFieldError("candidate_name", "Enter a valid name."); ok = false; }
    if (Number.isNaN(data.age) || data.age < 14 || data.age > 80) { setFieldError("age", "Age must be 14–80."); ok = false; }
    if (!data.education) { setFieldError("education", "Select an education level."); ok = false; }
    if (!data.relocate) { setFieldError("relocate", "Choose Yes or No."); ok = false; }
    if (Number.isNaN(data.skill_score) || data.skill_score < 0 || data.skill_score > 100) { setFieldError("skill_score", "Skill must be 0–100."); ok = false; }
    if (Number.isNaN(data.projects) || data.projects < 0) { setFieldError("projects", "Enter projects (0+)."); ok = false; }
    return ok;
  }

  /* ---------- Result panel ---------- */

  function renderResult(c) {
    $("#resultPlaceholder").hidden = true;
    $("#resultPanel").hidden = false;

    const s = statusInfo(c);
    const badge = $("#statusBadge");
    badge.textContent = c.priority_status ? "⭐ Priority Candidate" : c.eligibility;
    badge.className = `status-badge ${s.badge}`;

    $("#rankChip").textContent = `Rank: ${c.ranking_score}`;
    $("#salaryValue").textContent = c.salary_text;
    $("#confidenceValue").textContent = c.confidence_level;

    $("#skillMeter").style.width = `${c.skill_score}%`;
    $("#skillMeterLabel").textContent = `${c.skill_score}/100`;

    const pct = CONFIDENCE_PERCENT[c.confidence_level] || 0;
    $("#confMeter").style.width = `${pct}%`;
    $("#confMeterLabel").textContent = `${pct}%`;

    const list = $("#suggestionList");
    list.innerHTML = "";
    (c.suggestions || []).forEach((tip) => {
      const li = document.createElement("li");
      li.textContent = tip;
      list.appendChild(li);
    });

    $("#downloadBtn").onclick = () => downloadReport(c);
    $("#resultPanel").scrollIntoView({ behavior: "smooth", block: "nearest" });
  }

  function downloadReport(c) {
    const divider = "=".repeat(54);
    let tips = "";
    (c.suggestions || []).forEach((t, i) => { tips += `  ${i + 1}. ${t}\n`; });
    const text =
`${divider}
   TALENTSCOPE — CANDIDATE EVALUATION REPORT
${divider}

Candidate Name : ${c.candidate_name}
Age            : ${c.age}
Education      : ${c.education}
Relocate       : ${c.relocate}

------------------------------------------------------
  EVALUATION
------------------------------------------------------
Status            : ${c.priority_status ? "Priority Candidate" : c.eligibility}
JS Skill Score    : ${c.skill_score}/100
Projects          : ${c.projects}
Estimated Salary  : ${c.salary_text}
Confidence Level  : ${c.confidence_level}
Ranking Score     : ${c.ranking_score}

------------------------------------------------------
  IMPROVEMENT SUGGESTIONS
------------------------------------------------------
${tips}
${divider}
   Generated by TalentScope
${divider}
`;
    const safe = c.candidate_name.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
    downloadText(`report-${safe}.txt`, text);
    toast("Report downloaded.", "success");
  }

  function exportAll() {
    if (cache.length === 0) { toast("No candidates to export.", "info"); return; }
    const divider = "=".repeat(54);
    let body = `${divider}\n   TALENTSCOPE — CANDIDATE EXPORT\n${divider}\n\n`;
    body += `Total: ${cache.length}\n\n`;
    cache.forEach((c, i) => {
      body += `#${i + 1}  ${c.candidate_name}\n`;
      body += `    Status: ${c.priority_status ? "Priority" : c.eligibility} | Skill: ${c.skill_score} | Projects: ${c.projects}\n`;
      body += `    Salary: ${c.salary_text} | Confidence: ${c.confidence_level} | Rank: ${c.ranking_score}\n\n`;
    });
    downloadText("talentscope-candidates.txt", body);
    toast("Exported all candidates.", "success");
  }

  /* ---------- History table ---------- */

  function buildQuery() {
    const search = $("#searchInput").value.trim();
    const filter = $("#filterSelect").value;
    const sort = $("#sortSelect").value;
    const params = new URLSearchParams();
    if (search) params.set("search", search);
    if (filter && filter !== "all") params.set("filter", filter);
    if (sort) params.set("sort", sort);
    const qs = params.toString();
    return qs ? `?${qs}` : "";
  }

  async function loadHistory() {
    const loader = $("#historyLoader");
    const wrap = $("#historyWrap");
    const empty = $("#historyEmpty");
    loader.hidden = false;
    wrap.hidden = true;
    empty.hidden = true;

    try {
      const data = await window.API.get(`/candidates${buildQuery()}`);
      const list = data.candidates || [];
      cache = list;
      $("#historyCount").textContent = `${list.length} candidate${list.length === 1 ? "" : "s"}`;

      loader.hidden = true;
      if (list.length === 0) { empty.hidden = false; return; }

      let html = "";
      list.forEach((c, i) => {
        const s = statusInfo(c);
        html += `
          <tr>
            <td>${i + 1}</td>
            <td>${escapeHtml(c.candidate_name)}</td>
            <td>${c.age}</td>
            <td>${escapeHtml(c.education)}</td>
            <td><span class="pill pill-blue">${c.skill_score}</span></td>
            <td>${c.projects}</td>
            <td>${escapeHtml(c.salary_text)}</td>
            <td>${escapeHtml(c.confidence_level)}</td>
            <td>${c.ranking_score}</td>
            <td><span class="${s.cls}">${s.label}</span></td>
            <td>
              <div class="row-actions">
                <button class="icon-btn" data-edit="${c.id}" title="Edit">✏️</button>
                <button class="icon-btn" data-report="${c.id}" title="Download report">⬇️</button>
                <button class="icon-btn danger" data-del="${c.id}" title="Delete">🗑️</button>
              </div>
            </td>
          </tr>`;
      });
      $("#historyBody").innerHTML = html;
      wrap.hidden = false;

      // Wire row actions.
      document.querySelectorAll("[data-edit]").forEach((b) =>
        b.addEventListener("click", () => startEdit(Number(b.dataset.edit))));
      document.querySelectorAll("[data-report]").forEach((b) =>
        b.addEventListener("click", () => {
          const c = cache.find((x) => x.id === Number(b.dataset.report));
          if (c) downloadReport(c);
        }));
      document.querySelectorAll("[data-del]").forEach((b) =>
        b.addEventListener("click", () => removeCandidate(Number(b.dataset.del))));
    } catch (err) {
      loader.hidden = true;
      toast(err.message, "error");
    }
  }

  /* ---------- Create / Update / Delete ---------- */

  function startEdit(id) {
    const c = cache.find((x) => x.id === id);
    if (!c) return;
    editingId = id;
    $("#candidateId").value = id;
    $("#candidate_name").value = c.candidate_name;
    $("#age").value = c.age;
    $("#education").value = c.education;
    $("#relocate").value = c.relocate;
    $("#skill_score").value = c.skill_score;
    $("#skillOut").textContent = c.skill_score;
    $("#projects").value = c.projects;

    $("#formTitle").textContent = "✏️ Edit Candidate";
    $("#editingNote").hidden = false;
    $("#cancelEditBtn").hidden = false;
    $("#submitBtn").querySelector(".btn-text").textContent = "💾 Update Candidate";
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function cancelEdit() {
    editingId = null;
    $("#candidateForm").reset();
    $("#skillOut").textContent = $("#skill_score").value;
    clearErrors(FIELD_IDS);
    $("#formTitle").textContent = "📝 Evaluate a Candidate";
    $("#editingNote").hidden = true;
    $("#cancelEditBtn").hidden = true;
    $("#submitBtn").querySelector(".btn-text").textContent = "⚡ Evaluate & Save";
  }

  async function removeCandidate(id) {
    const c = cache.find((x) => x.id === id);
    if (!c) return;
    if (!window.confirm(`Delete "${c.candidate_name}"? This cannot be undone.`)) return;
    try {
      await window.API.del(`/candidates/${id}`);
      toast("Candidate deleted.", "info");
      if (editingId === id) cancelEdit();
      loadHistory();
    } catch (err) {
      toast(err.message, "error");
    }
  }

  async function handleSubmit(e) {
    e.preventDefault();
    const data = readForm();
    if (!validate(data)) { toast("Please fix the highlighted fields.", "error"); return; }

    const btn = $("#submitBtn");
    setLoading(btn, true, editingId ? "Updating…" : "Evaluating…");
    try {
      let candidate;
      if (editingId) {
        candidate = await window.API.put(`/candidates/${editingId}`, data);
        toast("Candidate updated.", "success");
      } else {
        candidate = await window.API.post("/candidates", data);
        toast("Candidate evaluated and saved.", "success");
      }
      renderResult(candidate.candidate);
      cancelEdit();
      loadHistory();
    } catch (err) {
      if (err.errors) err.errors.forEach((er) => setFieldError(er.field, er.message));
      toast(err.message, "error");
    } finally {
      setLoading(btn, false);
    }
  }

  /* ---------- Init ---------- */

  document.addEventListener("DOMContentLoaded", () => {
    const user = window.Auth.requireAuth();
    if (!user) return;
    window.Auth.initAppChrome("candidates");

    $("#skill_score").addEventListener("input", () => { $("#skillOut").textContent = $("#skill_score").value; });
    $("#candidateForm").addEventListener("submit", handleSubmit);
    $("#cancelEditBtn").addEventListener("click", cancelEdit);
    $("#resetBtn").addEventListener("click", () => setTimeout(cancelEdit, 0));
    $("#exportAllBtn").addEventListener("click", exportAll);

    $("#searchInput").addEventListener("input", debounce(loadHistory, 350));
    $("#filterSelect").addEventListener("change", loadHistory);
    $("#sortSelect").addEventListener("change", loadHistory);

    loadHistory();
  });
})();
